# Generated by Django 3.1 on 2020-10-05 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 8, 35, 22, 792726)),
        ),
    ]
