# Generated by Django 3.1 on 2020-10-06 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201005_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 15, 13, 29, 610997)),
        ),
    ]
