# Generated by Django 3.1 on 2020-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201006_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
